### PR TITLE
Added props "outerSpacing" and "showEmptySlots"

### PR DESCRIPTION
**Pull request by CannelleRb**

### CODE REVIEW

**Comment by CannelleRb** [comment]
Thanks a lot :) Do you have an idea of when the `next` branch will be merged, approximately ?

**Comment by sag1v** [comment]
Thank you!
I hope to merge and release it this weekend, i want to include some bug fixes and do a 1 release instead of couple releases for each issue.

**Comment by CannelleRb** [comment]
Ok thank you :) Yes, I would like a beta if that's possible for you !

**Comment by sag1v** [comment]
@CannelleRb I've published the `next` branch under the `next` tag (version `0.10.0-beta`).

So just install `react-elastic-carousel@next` and you should get the feature.
Let me know how its working for you :)

**Comment by CannelleRb** [comment]
It's working, thanks a lot :)

**Pull request merged**
