### PR TITLE
Add TypeScript typings

### PR DESCRIPTION
**Pull request by superjose**
Hello 😁. I hope this gets published in NPM soon!

Here are the typings! It's a manual process for now!

### CODE REVIEW

**Comment by sag1v** [comment]
I'm not a TS expert but aren't we missing the `types` property in `package.json`?

**Comment by superjose** [comment]
@sag1v Heheh 😁, you're right. I made the change.

**Comment by sag1v** [comment]
thank you 🙏

**Comment by sag1v** [comment]
resolve #34

**Pull request merged**
